/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Health Check
         * @description Health check endpoint.
         */
        get: operations["health_check_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/ready": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Readiness Check
         * @description Readiness check endpoint.
         */
        get: operations["readiness_check_ready_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/devices": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Devices
         * @description Query available devices from registry
         */
        get: operations["list_devices_api_v1_devices_get"];
        put?: never;
        /**
         * Create Runtime Device
         * @description Add a new device to the registry at runtime
         */
        post: operations["create_device_api_v1_devices_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/devices-info": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get All Devices Info
         * @description Get detailed metadata for all devices (ophyd-websocket compatible)
         */
        get: operations["get_all_devices_info_api_v1_devices_info_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/devices/classes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Device Classes
         * @description Get list of unique ophyd device classes (as-ophyd-api compatible)
         */
        get: operations["get_device_classes_api_v1_devices_classes_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/devices/types": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Device Types
         * @description Get list of device type categories
         */
        get: operations["get_device_labels_api_v1_devices_types_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/devices/instantiation": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Device Instantiation Specs
         * @description Get all device instantiation specifications for remote device creation
         */
        get: operations["list_device_instantiations_api_v1_devices_instantiation_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/devices/history": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Device Audit Log
         * @description List device change history (audit log of all mutations)
         */
        get: operations["list_device_history_api_v1_devices_history_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/devices/changes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Device Registry Delta
         * @description Return device-state changes after a given audit cursor. Intended for clients (like bluesky-queueserver) that cache device state and need to keep it fresh without re-fetching the full registry. Each device is reported at most once with its current state. If reset_occurred is true, the caller should discard local state and re-fetch /devices-info; likewise if service_epoch differs from a previously-observed value.
         */
        get: operations["get_device_changes_api_v1_devices_changes_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/devices/lock": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Lock Devices (Bulk Atomic)
         * @description Acquire locks on multiple devices atomically (all-or-nothing).
         *
         *     When a device is locked, all PVs belonging to that device are implicitly
         *     locked. Direct Control checks PV/device status before every write operation
         *     and will refuse to command locked PVs.
         *
         *     Locks are held for the duration of a Bluesky plan (minutes to hours).
         *     EE sends unlock when the plan completes, fails, or is aborted.
         */
        post: operations["lock_devices_api_v1_devices_lock_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/devices/unlock": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Unlock Devices
         * @description Release locks on devices. Only the item_id that acquired the lock can
         *     release it. Use force-unlock for admin override.
         */
        post: operations["unlock_devices_api_v1_devices_unlock_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/devices/force-unlock": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Force Unlock Devices (Admin)
         * @description Emergency endpoint to clear stale locks regardless of ownership.
         *
         *     Use when EE crashes mid-plan and locks are orphaned. Requires ADMIN
         *     role when AuthZ middleware is enabled.
         */
        post: operations["force_unlock_devices_api_v1_devices_force_unlock_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/devices/{device_name}/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Device Availability
         * @description Combined availability check: lock state + enabled/disabled.
         *
         *     A device is available only when it is both enabled and unlocked.
         */
        get: operations["get_device_status_api_v1_devices__device_name__status_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/devices/{device_name}/enable": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Enable Device
         * @description Enable a device so it will be instantiated by remote services
         */
        patch: operations["enable_device_api_v1_devices__device_name__enable_patch"];
        trace?: never;
    };
    "/api/v1/devices/{device_name}/disable": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Disable Device
         * @description Disable a device so it will not be instantiated by remote services
         */
        patch: operations["disable_device_api_v1_devices__device_name__disable_patch"];
        trace?: never;
    };
    "/api/v1/devices/{device_name}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Device Metadata
         * @description Get detailed metadata for specific device including PV mappings
         */
        get: operations["get_device_api_v1_devices__device_name__get"];
        /**
         * Update Device
         * @description Update an existing device's metadata and/or instantiation spec
         */
        put: operations["update_device_api_v1_devices__device_name__put"];
        post?: never;
        /**
         * Delete Device
         * @description Remove a device from the registry
         */
        delete: operations["delete_device_api_v1_devices__device_name__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/devices/{device_name}/pvs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Device PVs
         * @description Get all PVs owned by a device, mapped by component name
         */
        get: operations["get_device_pvs_api_v1_devices__device_name__pvs_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/devices/{device_name}/instantiation": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Device Instantiation Spec
         * @description Get instantiation specification for a specific device
         */
        get: operations["get_device_instantiation_api_v1_devices__device_name__instantiation_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/registry/reset": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Reset Registry
         * @description Wipe the device DB and re-seed from profile collection
         */
        post: operations["reset_registry_api_v1_registry_reset_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/registry/clear": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Clear Registry
         * @description Wipe all devices without re-seeding. The next restart will re-seed from the profile.
         */
        post: operations["clear_registry_api_v1_registry_clear_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/registry/export": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Export Registry
         * @description Export the device registry in a portable format (happi)
         */
        get: operations["export_registry_api_v1_registry_export_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/pvs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List PVs
         * @description Query available PVs from loaded devices
         */
        get: operations["list_pvs_api_v1_pvs_get"];
        put?: never;
        /**
         * Register Standalone PV
         * @description Register a standalone PV not associated with any ophyd device
         */
        post: operations["create_standalone_pv_api_v1_pvs_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/pvs/standalone": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Standalone PVs
         * @description List all registered standalone PVs with optional label filtering
         */
        get: operations["list_standalone_pvs_api_v1_pvs_standalone_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/pvs/labels": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Standalone PV Labels
         * @description Get all unique labels across registered standalone PVs
         */
        get: operations["list_standalone_pv_labels_api_v1_pvs_labels_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/pvs/standalone/{pv_name}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /**
         * Update Standalone PV
         * @description Update a registered standalone PV
         */
        put: operations["update_standalone_pv_api_v1_pvs_standalone__pv_name__put"];
        post?: never;
        /**
         * Delete Standalone PV
         * @description Remove a registered standalone PV
         */
        delete: operations["delete_standalone_pv_api_v1_pvs_standalone__pv_name__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/pvs/detailed": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Detailed PV Information
         * @description Get PVs organized by device with signal path information
         */
        get: operations["get_pvs_detailed_api_v1_pvs_detailed_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/pvs/lookup": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Lookup Device PVs by PV Name
         * @description Given a PV, find the owning device and return all PVs for that device
         */
        get: operations["lookup_device_pvs_by_pv_api_v1_pvs_lookup_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/pvs/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get PV Availability
         * @description Check whether a PV can be commanded (caput).
         *
         *     Resolves PV to its owning device and returns the device's lock and
         *     enabled state. Standalone PVs (not bound to a device) are always
         *     available. This is the primary endpoint Direct Control calls before
         *     every write operation.
         */
        get: operations["get_pv_status_api_v1_pvs_status_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/pvs/{pv_name}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get PV Metadata
         * @description Get detailed metadata for specific PV
         */
        get: operations["get_pv_api_v1_pvs__pv_name__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/devices/{device_path}/component": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Nested Device Component
         * @description Look up nested device component by dot-separated path
         */
        get: operations["get_nested_device_component_api_v1_devices__device_path__component_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/devices/{device_name}/components": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Device Components
         * @description List all components of a device
         */
        get: operations["list_device_components_api_v1_devices__device_name__components_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/metadata": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Metadata Entries
         * @description List all stored metadata key-value entries
         */
        get: operations["list_metadata_api_v1_metadata_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/metadata/{key}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Metadata Entry
         * @description Get a single metadata entry by key
         */
        get: operations["get_metadata_api_v1_metadata__key__get"];
        /**
         * Create or Update Metadata Entry
         * @description Upsert a metadata key-value entry
         */
        put: operations["upsert_metadata_api_v1_metadata__key__put"];
        /**
         * Create Metadata Entry
         * @description Create a new metadata key-value entry (409 if key exists)
         */
        post: operations["create_metadata_api_v1_metadata__key__post"];
        /**
         * Delete Metadata Entry
         * @description Delete a metadata key-value entry
         */
        delete: operations["delete_metadata_api_v1_metadata__key__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * DeviceAuditEntry
         * @description Entry in the device audit log (append-only change history).
         */
        DeviceAuditEntry: {
            /**
             * Id
             * @description Auto-incrementing audit log entry ID
             */
            id: number;
            /**
             * Device Name
             * @description Device name (or '*' for registry-wide ops)
             */
            device_name: string;
            /**
             * Operation
             * @description Operation (seed/add/update/delete/reset)
             */
            operation: string;
            /**
             * Timestamp
             * @description Unix timestamp
             */
            timestamp: number;
            /**
             * Details
             * @description Optional JSON details
             */
            details?: string | null;
        };
        /**
         * DeviceCRUDResponse
         * @description Response model for device CRUD operations.
         */
        DeviceCRUDResponse: {
            /**
             * Success
             * @description Whether the operation succeeded
             */
            success: boolean;
            /**
             * Device Name
             * @description Name of the device
             */
            device_name: string;
            /**
             * Operation
             * @description Operation performed (create/update/delete)
             */
            operation: string;
            /**
             * Message
             * @description Human-readable status message
             */
            message: string;
        };
        /**
         * DeviceChangeEntry
         * @description One device's current state, reported in a delta response.
         *
         *     ``op`` is "upsert" if the device currently exists (create or update), or
         *     "delete" if it no longer exists. For "upsert", ``metadata`` and ``spec``
         *     reflect the current state; for "delete" both are null.
         */
        DeviceChangeEntry: {
            /**
             * Device Name
             * @description Device name
             */
            device_name: string;
            /**
             * Op
             * @description Either 'upsert' or 'delete'
             * @enum {string}
             */
            op: "upsert" | "delete";
            /**
             * Version
             * @description Audit log id of the change that produced this state
             */
            version: number;
            metadata?: components["schemas"]["DeviceMetadata"] | null;
            spec?: components["schemas"]["DeviceInstantiationSpec"] | null;
        };
        /**
         * DeviceChangesResponse
         * @description Delta response: every device whose state changed after ``since_version``.
         *
         *     If ``reset_occurred`` is true, a registry-wide reset happened in the
         *     requested range and the caller should discard its local state and
         *     re-fetch the full registry instead of applying ``changes`` incrementally.
         *     ``service_epoch`` is a stable identifier that changes only on manual
         *     re-seed or DB wipe; if it differs from the value the caller saw last,
         *     treat the cursor as invalid.
         */
        DeviceChangesResponse: {
            /**
             * Current Version
             * @description Latest audit log id at query time
             */
            current_version: number;
            /**
             * Service Epoch
             * @description Stable service-instance identifier
             */
            service_epoch: string;
            /**
             * Reset Occurred
             * @description True if a registry-wide reset happened in the range
             */
            reset_occurred: boolean;
            /** Changes */
            changes?: components["schemas"]["DeviceChangeEntry"][];
        };
        /**
         * DeviceCreateRequest
         * @description Request model for creating a runtime device.
         * @example {
         *       "instantiation_spec": {
         *         "args": [
         *           "NEW:MOTOR"
         *         ],
         *         "device_class": "ophyd.EpicsMotor",
         *         "kwargs": {
         *           "name": "new_motor"
         *         },
         *         "name": "new_motor"
         *       },
         *       "metadata": {
         *         "device_label": "motor",
         *         "is_movable": true,
         *         "is_readable": true,
         *         "name": "new_motor",
         *         "ophyd_class": "EpicsMotor",
         *         "pvs": {
         *           "user_readback": "NEW:MOTOR.RBV",
         *           "user_setpoint": "NEW:MOTOR"
         *         }
         *       }
         *     }
         */
        DeviceCreateRequest: {
            /** @description Device metadata */
            metadata: components["schemas"]["DeviceMetadata"];
            /** @description Device instantiation specification */
            instantiation_spec: components["schemas"]["DeviceInstantiationSpec"];
        };
        /**
         * DeviceForceUnlockRequest
         * @description Request model for administrative force-unlock.
         * @example {
         *       "device_names": [
         *         "sample_x"
         *       ],
         *       "reason": "EE crashed during rel_scan, clearing stale locks"
         *     }
         */
        DeviceForceUnlockRequest: {
            /**
             * Device Names
             * @description Devices to force-unlock
             */
            device_names: string[];
            /**
             * Reason
             * @description Reason for force-unlock (for audit log)
             */
            reason: string;
        };
        /**
         * DeviceInstantiationSpec
         * @description Device instantiation specification for remote device creation.
         *
         *     This model contains all information needed to recreate a device instance
         *     in another service (e.g., Experiment Execution Service). By providing
         *     the class path and constructor arguments, remote services can dynamically
         *     import and instantiate identical device objects.
         *
         *     This enables Configuration Service to be the single source of truth for
         *     device definitions, ensuring PV names and configurations are consistent
         *     across all services.
         * @example {
         *       "active": true,
         *       "args": [
         *         "BL01:DET1:"
         *       ],
         *       "device_class": "ophyd.EpicsScaler",
         *       "kwargs": {
         *         "name": "det1"
         *       },
         *       "name": "det1"
         *     }
         */
        DeviceInstantiationSpec: {
            /**
             * Name
             * @description Device name from profile collection
             */
            name: string;
            /**
             * Device Class
             * @description Fully qualified class path (e.g., 'ophyd.EpicsMotor', 'ophyd.EpicsScaler')
             */
            device_class: string;
            /**
             * Args
             * @description Positional arguments for device constructor (e.g., ['BL01:DET1:'])
             */
            args?: unknown[];
            /**
             * Kwargs
             * @description Keyword arguments for device constructor (e.g., {'name': 'det1'})
             */
            kwargs?: Record<string, never>;
            /**
             * Active
             * @description Whether this device should be instantiated
             * @default true
             */
            active: boolean;
        };
        /** DeviceInstantiationSpecUpdate */
        DeviceInstantiationSpecUpdate: {
            /**
             * Name
             * @description Device name from profile collection
             */
            name?: string | null;
            /**
             * Device Class
             * @description Fully qualified class path (e.g., 'ophyd.EpicsMotor', 'ophyd.EpicsScaler')
             */
            device_class?: string | null;
            /**
             * Args
             * @description Positional arguments for device constructor (e.g., ['BL01:DET1:'])
             */
            args?: unknown[] | null;
            /**
             * Kwargs
             * @description Keyword arguments for device constructor (e.g., {'name': 'det1'})
             */
            kwargs?: Record<string, never> | null;
            /**
             * Active
             * @description Whether this device should be instantiated
             */
            active?: boolean | null;
        };
        /**
         * DeviceLabel
         * @description Device classification derived from ophyd/ophyd-async class hierarchy.
         *
         *     Each value maps directly to a concrete base class in ophyd or ophyd-async:
         *       MOTOR     — ophyd.EpicsMotor, ophyd_async.epics.motor.Motor
         *       DETECTOR  — ophyd.areadetector.DetectorBase, ophyd_async.core.StandardDetector
         *       SIGNAL    — ophyd.Signal/EpicsSignal, ophyd_async.core.Signal
         *       FLYER     — ophyd.FlyerInterface, ophyd_async.core.StandardFlyer
         *       READABLE  — ophyd_async.core.StandardReadable (readable but not motor/detector)
         *       DEVICE    — ophyd.Device, ophyd_async.core.Device (generic base)
         * @enum {string}
         */
        DeviceLabel: "motor" | "detector" | "signal" | "flyer" | "readable" | "device";
        /**
         * DeviceLockConflict
         * @description A single device that could not be locked.
         */
        DeviceLockConflict: {
            /**
             * Device Name
             * @description Device name
             */
            device_name: string;
            /**
             * Reason
             * @description Why the lock failed (not_found, disabled, already_locked)
             */
            reason: string;
            /**
             * Locked By Plan
             * @description Plan holding the lock
             */
            locked_by_plan?: string | null;
            /**
             * Locked At
             * @description ISO timestamp of lock acquisition
             */
            locked_at?: string | null;
        };
        /**
         * DeviceLockConflictResponse
         * @description Response model for lock conflict (409/404/422).
         */
        DeviceLockConflictResponse: {
            /**
             * Success
             * @default false
             */
            success: boolean;
            /**
             * Message
             * @description Human-readable error message
             */
            message: string;
            /**
             * Conflicting Devices
             * @description Devices that caused the conflict
             */
            conflicting_devices?: components["schemas"]["DeviceLockConflict"][];
        };
        /**
         * DeviceLockRequest
         * @description Request model for acquiring device locks (bulk atomic).
         * @example {
         *       "device_names": [
         *         "sample_x",
         *         "det1"
         *       ],
         *       "item_id": "550e8400-e29b-41d4-a716-446655440000",
         *       "locked_by_service": "experiment_execution",
         *       "plan_name": "count"
         *     }
         */
        DeviceLockRequest: {
            /**
             * Device Names
             * @description Devices to lock
             */
            device_names: string[];
            /**
             * Item Id
             * @description Queue item ID holding the lock
             */
            item_id: string;
            /**
             * Plan Name
             * @description Name of the plan acquiring devices
             */
            plan_name: string;
            /**
             * Locked By Service
             * @description Service requesting the lock
             * @default experiment_execution
             */
            locked_by_service: string;
        };
        /**
         * DeviceLockResponse
         * @description Response model for successful lock acquisition.
         */
        DeviceLockResponse: {
            /**
             * Success
             * @description Whether locks were acquired
             */
            success: boolean;
            /**
             * Locked Devices
             * @description Devices that were locked
             */
            locked_devices?: string[];
            /**
             * Locked Pvs
             * @description PVs implicitly locked
             */
            locked_pvs?: string[];
            /**
             * Lock Id
             * @description Lock group identifier
             */
            lock_id?: string | null;
            /**
             * Registry Version
             * @description Lock version counter
             */
            registry_version: number;
        };
        /**
         * DeviceMetadata
         * @description Device metadata model.
         *
         *     Represents device information loaded from profile collections.
         *     Maps to ProvidesDeviceRegistry.get_device() return type.
         *
         *     Compatible with ophyd/ophyd-async device introspection and profile collection formats.
         * @example {
         *       "configuration_attrs": [
         *         "velocity",
         *         "acceleration"
         *       ],
         *       "device_label": "motor",
         *       "hints": {
         *         "fields": [
         *           "sample_x"
         *         ]
         *       },
         *       "is_checkable": true,
         *       "is_configurable": true,
         *       "is_flyable": false,
         *       "is_movable": true,
         *       "is_pausable": false,
         *       "is_readable": true,
         *       "is_stageable": true,
         *       "is_stoppable": true,
         *       "is_subscribable": true,
         *       "is_triggerable": true,
         *       "module": "ophyd.epics_motor",
         *       "name": "sample_x",
         *       "ophyd_class": "EpicsMotor",
         *       "pvs": {
         *         "user_readback": "BL01:SAMPLE:X.RBV",
         *         "user_setpoint": "BL01:SAMPLE:X",
         *         "velocity": "BL01:SAMPLE:X.VELO"
         *       },
         *       "read_attrs": [
         *         "user_readback",
         *         "user_setpoint"
         *       ],
         *       "writes_external_assets": false
         *     }
         */
        DeviceMetadata: {
            /**
             * Name
             * @description Device name from profile collection
             */
            name: string;
            /** @description Classification of device */
            device_label: components["schemas"]["DeviceLabel"];
            /**
             * Ophyd Class
             * @description Ophyd device class name
             */
            ophyd_class: string;
            /**
             * Module
             * @description Python module containing the device class
             */
            module?: string | null;
            /**
             * Is Movable
             * @description Implements Movable protocol
             * @default false
             */
            is_movable: boolean;
            /**
             * Is Flyable
             * @description Implements Flyable protocol
             * @default false
             */
            is_flyable: boolean;
            /**
             * Is Readable
             * @description Implements Readable protocol
             * @default false
             */
            is_readable: boolean;
            /**
             * Is Triggerable
             * @description Implements Triggerable protocol (has trigger)
             * @default false
             */
            is_triggerable: boolean;
            /**
             * Is Stageable
             * @description Implements Stageable protocol (has stage/unstage)
             * @default false
             */
            is_stageable: boolean;
            /**
             * Is Configurable
             * @description Implements Configurable protocol (has read_configuration/describe_configuration)
             * @default false
             */
            is_configurable: boolean;
            /**
             * Is Pausable
             * @description Implements Pausable protocol (has pause/resume)
             * @default false
             */
            is_pausable: boolean;
            /**
             * Is Stoppable
             * @description Implements Stoppable protocol (has stop)
             * @default false
             */
            is_stoppable: boolean;
            /**
             * Is Subscribable
             * @description Implements Subscribable protocol (has subscribe/clear_sub)
             * @default false
             */
            is_subscribable: boolean;
            /**
             * Is Checkable
             * @description Implements Checkable protocol (has check_value)
             * @default false
             */
            is_checkable: boolean;
            /**
             * Writes External Assets
             * @description Writes external assets (has collect_asset_docs)
             * @default false
             */
            writes_external_assets: boolean;
            /**
             * Pvs
             * @description Component name to PV mapping
             */
            pvs?: {
                [key: string]: string;
            };
            /**
             * Hints
             * @description Bluesky hints for plotting/display
             */
            hints?: Record<string, never> | null;
            /**
             * Read Attrs
             * @description Readable attributes
             */
            read_attrs?: string[];
            /**
             * Configuration Attrs
             * @description Configuration attributes
             */
            configuration_attrs?: string[];
            /**
             * Parent
             * @description Parent device if this is a component
             */
            parent?: string | null;
            /**
             * Labels
             * @description Device labels for grouping (e.g., 'motors', 'detectors', 'baseline')
             */
            labels?: string[];
            /**
             * Beamline
             * @description Beamline identifier (from happi)
             */
            beamline?: string | null;
            /**
             * Location Group
             * @description Location grouping (from happi)
             */
            location_group?: string | null;
            /**
             * Functional Group
             * @description Functional grouping (from happi)
             */
            functional_group?: string | null;
            /**
             * Documentation
             * @description Device documentation/description
             */
            documentation?: string | null;
        };
        /** DeviceMetadataUpdate */
        DeviceMetadataUpdate: {
            /**
             * Name
             * @description Device name from profile collection
             */
            name?: string | null;
            /** @description Classification of device */
            device_label?: components["schemas"]["DeviceLabel"] | null;
            /**
             * Ophyd Class
             * @description Ophyd device class name
             */
            ophyd_class?: string | null;
            /**
             * Module
             * @description Python module containing the device class
             */
            module?: string | null;
            /**
             * Is Movable
             * @description Implements Movable protocol
             */
            is_movable?: boolean | null;
            /**
             * Is Flyable
             * @description Implements Flyable protocol
             */
            is_flyable?: boolean | null;
            /**
             * Is Readable
             * @description Implements Readable protocol
             */
            is_readable?: boolean | null;
            /**
             * Is Triggerable
             * @description Implements Triggerable protocol (has trigger)
             */
            is_triggerable?: boolean | null;
            /**
             * Is Stageable
             * @description Implements Stageable protocol (has stage/unstage)
             */
            is_stageable?: boolean | null;
            /**
             * Is Configurable
             * @description Implements Configurable protocol (has read_configuration/describe_configuration)
             */
            is_configurable?: boolean | null;
            /**
             * Is Pausable
             * @description Implements Pausable protocol (has pause/resume)
             */
            is_pausable?: boolean | null;
            /**
             * Is Stoppable
             * @description Implements Stoppable protocol (has stop)
             */
            is_stoppable?: boolean | null;
            /**
             * Is Subscribable
             * @description Implements Subscribable protocol (has subscribe/clear_sub)
             */
            is_subscribable?: boolean | null;
            /**
             * Is Checkable
             * @description Implements Checkable protocol (has check_value)
             */
            is_checkable?: boolean | null;
            /**
             * Writes External Assets
             * @description Writes external assets (has collect_asset_docs)
             */
            writes_external_assets?: boolean | null;
            /**
             * Pvs
             * @description Component name to PV mapping
             */
            pvs?: {
                [key: string]: string;
            } | null;
            /**
             * Hints
             * @description Bluesky hints for plotting/display
             */
            hints?: Record<string, never> | null;
            /**
             * Read Attrs
             * @description Readable attributes
             */
            read_attrs?: string[] | null;
            /**
             * Configuration Attrs
             * @description Configuration attributes
             */
            configuration_attrs?: string[] | null;
            /**
             * Parent
             * @description Parent device if this is a component
             */
            parent?: string | null;
            /**
             * Labels
             * @description Device labels for grouping (e.g., 'motors', 'detectors', 'baseline')
             */
            labels?: string[] | null;
            /**
             * Beamline
             * @description Beamline identifier (from happi)
             */
            beamline?: string | null;
            /**
             * Location Group
             * @description Location grouping (from happi)
             */
            location_group?: string | null;
            /**
             * Functional Group
             * @description Functional grouping (from happi)
             */
            functional_group?: string | null;
            /**
             * Documentation
             * @description Device documentation/description
             */
            documentation?: string | null;
        };
        /**
         * DeviceStatusResponse
         * @description Combined device availability check (lock + enabled state).
         */
        DeviceStatusResponse: {
            /**
             * Device Name
             * @description Device name
             */
            device_name: string;
            /**
             * Available
             * @description True only when enabled AND unlocked
             */
            available: boolean;
            /**
             * Enabled
             * @description Whether the device is enabled for instantiation
             */
            enabled: boolean;
            /**
             * Lock Status
             * @description Lock state: 'locked' or 'unlocked'
             */
            lock_status: string;
            /**
             * Locked By Plan
             * @description Plan holding the lock
             */
            locked_by_plan?: string | null;
            /**
             * Locked By Item
             * @description Queue item ID holding the lock
             */
            locked_by_item?: string | null;
            /**
             * Locked At
             * @description ISO timestamp of lock acquisition
             */
            locked_at?: string | null;
        };
        /**
         * DeviceUnlockRequest
         * @description Request model for releasing device locks.
         */
        DeviceUnlockRequest: {
            /**
             * Device Names
             * @description Devices to unlock
             */
            device_names: string[];
            /**
             * Item Id
             * @description Queue item ID that holds the lock
             */
            item_id: string;
        };
        /**
         * DeviceUnlockResponse
         * @description Response model for unlock operations.
         */
        DeviceUnlockResponse: {
            /**
             * Success
             * @description Whether locks were released
             */
            success: boolean;
            /**
             * Unlocked Devices
             * @description Devices that were unlocked
             */
            unlocked_devices?: string[];
            /**
             * Registry Version
             * @description Lock version counter
             */
            registry_version: number;
        };
        /**
         * DeviceUpdateRequest
         * @description Request model for updating a device.
         *
         *     Supports field-level partial updates: only the fields you include
         *     in ``metadata`` or ``instantiation_spec`` are changed.  Omitted fields
         *     keep their current values.
         * @example {
         *       "metadata": {
         *         "documentation": "Sample X translation stage",
         *         "labels": [
         *           "motors",
         *           "sample-stage"
         *         ]
         *       }
         *     }
         */
        DeviceUpdateRequest: {
            /** @description Partial device metadata — only included fields are updated */
            metadata?: components["schemas"]["DeviceMetadataUpdate"] | null;
            /** @description Partial instantiation spec — only included fields are updated */
            instantiation_spec?: components["schemas"]["DeviceInstantiationSpecUpdate"] | null;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /**
         * MetadataCRUDResponse
         * @description Response model for metadata CRUD operations.
         */
        MetadataCRUDResponse: {
            /**
             * Success
             * @description Whether the operation succeeded
             */
            success: boolean;
            /**
             * Key
             * @description Metadata key
             */
            key: string;
            /**
             * Operation
             * @description Operation performed (create/update/delete)
             */
            operation: string;
            /**
             * Message
             * @description Human-readable status message
             */
            message: string;
        };
        /**
         * MetadataEntry
         * @description A stored metadata key-value entry.
         */
        MetadataEntry: {
            /**
             * Key
             * @description Unique string key
             */
            key: string;
            /**
             * Value
             * @description Arbitrary JSON dictionary
             */
            value: Record<string, never>;
            /**
             * Created At
             * @description Unix timestamp of creation
             */
            created_at?: number | null;
            /**
             * Updated At
             * @description Unix timestamp of last update
             */
            updated_at?: number | null;
        };
        /**
         * MetadataWriteRequest
         * @description Request model for creating or updating a metadata entry.
         */
        MetadataWriteRequest: {
            /**
             * Value
             * @description Arbitrary JSON dictionary to store
             */
            value: Record<string, never>;
        };
        /**
         * NestedDeviceComponent
         * @description Information about a nested device component.
         */
        NestedDeviceComponent: {
            /**
             * Name
             * @description Component name
             */
            name: string;
            /**
             * Device Path
             * @description Full path to component
             */
            device_path: string;
            /**
             * Parent Device
             * @description Parent device name
             */
            parent_device: string;
            /**
             * Component Type
             * @description Component type
             */
            component_type?: string | null;
            /**
             * Pv
             * @description Associated EPICS PV
             */
            pv?: string | null;
            /**
             * Is Readable
             * @description Whether component is readable
             * @default true
             */
            is_readable: boolean;
            /**
             * Is Settable
             * @description Whether component is settable
             * @default false
             */
            is_settable: boolean;
        };
        /**
         * PVAccessMode
         * @description Access mode for standalone PVs.
         * @enum {string}
         */
        PVAccessMode: "read-only" | "read-write";
        /**
         * PVMetadata
         * @description EPICS PV metadata model.
         *
         *     Represents PV information from EPICS network discovery.
         *     Maps to ProvidesDeviceRegistry.get_pv_metadata() return type.
         * @example {
         *       "component_name": "user_readback",
         *       "connected": true,
         *       "device_name": "sample_x",
         *       "dtype": "double",
         *       "lower_ctrl_limit": -100,
         *       "precision": 3,
         *       "pv": "BL01:SAMPLE:X.RBV",
         *       "units": "mm",
         *       "upper_ctrl_limit": 100
         *     }
         */
        PVMetadata: {
            /**
             * Pv
             * @description EPICS PV name
             */
            pv: string;
            /**
             * Connected
             * @description Connection status
             * @default false
             */
            connected: boolean;
            /**
             * Dtype
             * @description EPICS data type
             */
            dtype?: string | null;
            /**
             * Units
             * @description Engineering units
             */
            units?: string | null;
            /**
             * Precision
             * @description Display precision
             */
            precision?: number | null;
            /**
             * Enum Strs
             * @description Enumeration strings for enum PVs
             */
            enum_strs?: string[] | null;
            /**
             * Upper Ctrl Limit
             * @description Upper control limit
             */
            upper_ctrl_limit?: number | null;
            /**
             * Lower Ctrl Limit
             * @description Lower control limit
             */
            lower_ctrl_limit?: number | null;
            /**
             * Device Name
             * @description Owning device name if known
             */
            device_name?: string | null;
            /**
             * Component Name
             * @description Component name within device
             */
            component_name?: string | null;
        };
        /**
         * PVProtocol
         * @description EPICS protocol for standalone PV access.
         * @enum {string}
         */
        PVProtocol: "ca" | "pva";
        /**
         * PVStatusResponse
         * @description PV availability check (resolves PV to owning device lock state).
         */
        PVStatusResponse: {
            /**
             * Pv Name
             * @description EPICS PV name
             */
            pv_name: string;
            /**
             * Available
             * @description True when owning device is enabled and unlocked (or standalone)
             */
            available: boolean;
            /**
             * Device Name
             * @description Owning device name (null for standalone PVs)
             */
            device_name?: string | null;
            /**
             * Device Enabled
             * @description Whether the owning device is enabled
             */
            device_enabled?: boolean | null;
            /**
             * Device Lock Status
             * @description Owning device lock state
             */
            device_lock_status?: string | null;
            /**
             * Locked By Plan
             * @description Plan holding the lock on the owning device
             */
            locked_by_plan?: string | null;
            /**
             * Locked By Item
             * @description Queue item ID holding the lock
             */
            locked_by_item?: string | null;
            /**
             * Locked At
             * @description ISO timestamp of lock acquisition
             */
            locked_at?: string | null;
        };
        /**
         * StandalonePV
         * @description A standalone PV not associated with any ophyd device.
         */
        StandalonePV: {
            /**
             * Pv Name
             * @description EPICS PV name
             */
            pv_name: string;
            /**
             * Description
             * @description Human-readable description
             */
            description?: string | null;
            /**
             * @description EPICS protocol
             * @default ca
             */
            protocol: components["schemas"]["PVProtocol"];
            /**
             * @description Access mode
             * @default read-only
             */
            access_mode: components["schemas"]["PVAccessMode"];
            /**
             * Labels
             * @description Labels for RBAC grouping
             */
            labels?: string[];
            /**
             * Source
             * @description Source of registration
             * @default runtime
             */
            source: string;
            /**
             * Created By
             * @description User who registered this PV
             */
            created_by?: string | null;
            /**
             * Created At
             * @description Unix timestamp of creation
             */
            created_at?: number | null;
            /**
             * Updated At
             * @description Unix timestamp of last update
             */
            updated_at?: number | null;
        };
        /**
         * StandalonePVCRUDResponse
         * @description Response model for standalone PV CRUD operations.
         */
        StandalonePVCRUDResponse: {
            /**
             * Success
             * @description Whether the operation succeeded
             */
            success: boolean;
            /**
             * Pv Name
             * @description PV name
             */
            pv_name: string;
            /**
             * Operation
             * @description Operation performed (create/update/delete)
             */
            operation: string;
            /**
             * Message
             * @description Human-readable status message
             */
            message: string;
        };
        /**
         * StandalonePVCreateRequest
         * @description Request model for registering a standalone PV.
         * @example {
         *       "access_mode": "read-only",
         *       "description": "Storage ring beam current",
         *       "labels": [
         *         "machine",
         *         "beam-diagnostics"
         *       ],
         *       "protocol": "ca",
         *       "pv_name": "BL01:RING:CURRENT"
         *     }
         */
        StandalonePVCreateRequest: {
            /**
             * Pv Name
             * @description EPICS PV name
             */
            pv_name: string;
            /**
             * Description
             * @description Human-readable description
             */
            description?: string | null;
            /**
             * @description EPICS protocol
             * @default ca
             */
            protocol: components["schemas"]["PVProtocol"];
            /**
             * @description Access mode
             * @default read-only
             */
            access_mode: components["schemas"]["PVAccessMode"];
            /**
             * Labels
             * @description Labels for RBAC grouping
             */
            labels?: string[];
        };
        /**
         * StandalonePVUpdateRequest
         * @description Request model for updating a standalone PV.
         *
         *     All fields optional.  Only fields included in the request body are
         *     applied; omitted fields keep their current values.
         * @example {
         *       "description": "Updated: storage ring beam current (averaged)",
         *       "labels": [
         *         "machine",
         *         "beam-diagnostics",
         *         "averaging"
         *       ]
         *     }
         */
        StandalonePVUpdateRequest: {
            /**
             * Description
             * @description Human-readable description
             */
            description?: string | null;
            /** @description EPICS protocol */
            protocol?: components["schemas"]["PVProtocol"] | null;
            /** @description Access mode */
            access_mode?: components["schemas"]["PVAccessMode"] | null;
            /**
             * Labels
             * @description Labels for RBAC grouping
             */
            labels?: string[] | null;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_check_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    readiness_check_ready_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    list_devices_api_v1_devices_get: {
        parameters: {
            query?: {
                /** @description Filter by device type */
                device_label?: components["schemas"]["DeviceLabel"] | null;
                /** @description Glob pattern for name matching */
                pattern?: string | null;
                /** @description Filter by ophyd device class name */
                ophyd_class?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": string[];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_device_api_v1_devices_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DeviceCreateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DeviceCRUDResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_all_devices_info_api_v1_devices_info_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: components["schemas"]["DeviceMetadata"];
                    };
                };
            };
        };
    };
    get_device_classes_api_v1_devices_classes_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": string[];
                };
            };
        };
    };
    get_device_labels_api_v1_devices_types_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": string[];
                };
            };
        };
    };
    list_device_instantiations_api_v1_devices_instantiation_get: {
        parameters: {
            query?: {
                /** @description Only return active devices */
                active_only?: boolean;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: components["schemas"]["DeviceInstantiationSpec"];
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_device_history_api_v1_devices_history_get: {
        parameters: {
            query?: {
                /** @description Filter to a specific device */
                device_name?: string | null;
                /** @description Max entries to return */
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DeviceAuditEntry"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_device_changes_api_v1_devices_changes_get: {
        parameters: {
            query?: {
                /** @description Return changes with audit id greater than this value */
                since_version?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DeviceChangesResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    lock_devices_api_v1_devices_lock_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DeviceLockRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DeviceLockResponse"];
                };
            };
            /** @description One or more devices not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DeviceLockConflictResponse"];
                };
            };
            /** @description One or more devices already locked */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DeviceLockConflictResponse"];
                };
            };
            /** @description One or more devices are disabled */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DeviceLockConflictResponse"];
                };
            };
        };
    };
    unlock_devices_api_v1_devices_unlock_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DeviceUnlockRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DeviceUnlockResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    force_unlock_devices_api_v1_devices_force_unlock_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DeviceForceUnlockRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DeviceUnlockResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_device_status_api_v1_devices__device_name__status_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                device_name: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DeviceStatusResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    enable_device_api_v1_devices__device_name__enable_patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                device_name: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DeviceCRUDResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    disable_device_api_v1_devices__device_name__disable_patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                device_name: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DeviceCRUDResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_device_api_v1_devices__device_name__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                device_name: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DeviceMetadata"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_device_api_v1_devices__device_name__put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                device_name: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DeviceUpdateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DeviceCRUDResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_device_api_v1_devices__device_name__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                device_name: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DeviceCRUDResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_device_pvs_api_v1_devices__device_name__pvs_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                device_name: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": Record<string, never>;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_device_instantiation_api_v1_devices__device_name__instantiation_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                device_name: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DeviceInstantiationSpec"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    reset_registry_api_v1_registry_reset_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DeviceCRUDResponse"];
                };
            };
        };
    };
    clear_registry_api_v1_registry_clear_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DeviceCRUDResponse"];
                };
            };
        };
    };
    export_registry_api_v1_registry_export_get: {
        parameters: {
            query?: {
                /** @description Export format (currently only 'happi') */
                format?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_pvs_api_v1_pvs_get: {
        parameters: {
            query?: {
                /** @description Glob pattern for PV name matching */
                pattern?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": Record<string, never>;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_standalone_pv_api_v1_pvs_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["StandalonePVCreateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StandalonePVCRUDResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_standalone_pvs_api_v1_pvs_standalone_get: {
        parameters: {
            query?: {
                /** @description Comma-separated labels to filter by */
                labels?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StandalonePV"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_standalone_pv_labels_api_v1_pvs_labels_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": string[];
                };
            };
        };
    };
    update_standalone_pv_api_v1_pvs_standalone__pv_name__put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                pv_name: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["StandalonePVUpdateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StandalonePVCRUDResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_standalone_pv_api_v1_pvs_standalone__pv_name__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                pv_name: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StandalonePVCRUDResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_pvs_detailed_api_v1_pvs_detailed_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": Record<string, never>;
                };
            };
        };
    };
    lookup_device_pvs_by_pv_api_v1_pvs_lookup_get: {
        parameters: {
            query: {
                /** @description PV name to look up */
                pv_name: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": Record<string, never>;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_pv_status_api_v1_pvs_status_get: {
        parameters: {
            query: {
                /** @description EPICS PV name to check */
                pv_name: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PVStatusResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_pv_api_v1_pvs__pv_name__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                pv_name: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PVMetadata"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_nested_device_component_api_v1_devices__device_path__component_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                device_path: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NestedDeviceComponent"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_device_components_api_v1_devices__device_name__components_get: {
        parameters: {
            query?: {
                /** @description Maximum component depth (0 = all, 1 = top-level only) */
                max_depth?: number | null;
            };
            header?: never;
            path: {
                device_name: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NestedDeviceComponent"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_metadata_api_v1_metadata_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MetadataEntry"][];
                };
            };
        };
    };
    get_metadata_api_v1_metadata__key__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                key: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MetadataEntry"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    upsert_metadata_api_v1_metadata__key__put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                key: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MetadataWriteRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MetadataCRUDResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_metadata_api_v1_metadata__key__post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                key: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MetadataWriteRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MetadataCRUDResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_metadata_api_v1_metadata__key__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                key: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MetadataCRUDResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
