/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Health Check
         * @description Combined health check: coordination availability and monitoring stats.
         */
        get: operations["health_check_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/stats": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Stats */
        get: operations["get_stats_api_v1_stats_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/pv/set": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Set Pv
         * @description Set EPICS PV value with coordination check (Low Fidelity Channel).
         *
         *     Two modes:
         *     - wait=False (fire-and-forget, default): Issues write, returns immediately.
         *     - wait=True (put-completion): Waits for EPICS put-completion callback.
         *
         *     Raises 404 if PV not in registry, 423 if device locked, 503 if
         *     coordination service unavailable.
         */
        post: operations["set_pv_api_v1_pv_set_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/pv/{pv_name}/value": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Pv Value From Controller
         * @description One-shot CA get via DeviceController (no subscription).
         *
         *     Exposes the pyepics caget / ca.get knobs as query params. Returns a
         *     tiled-style envelope: JSON by default with `shape`/`dtype`/`ndim`/
         *     `nbytes` alongside the value; `Accept: application/octet-stream` (or
         *     `?format=binary`) returns raw bytes with the same metadata in
         *     `X-PV-*` headers.
         */
        get: operations["get_pv_value_from_controller_api_v1_pv__pv_name__value_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/pvs/{pv_name}/value": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Monitored Pv Value
         * @description Get current value of a PV from the monitoring subscription cache.
         *
         *     Subscribes to the PV if not already subscribed. Returns the same
         *     tiled-style envelope as the one-shot endpoint plus the monitor's
         *     full metadata (connected, alarm, limits, units, access flags).
         */
        get: operations["get_monitored_pv_value_api_v1_pvs__pv_name__value_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/pvs/connected": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Connected Pvs
         * @description List PVs currently connected in the monitoring subsystem.
         */
        get: operations["get_connected_pvs_api_v1_pvs_connected_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/device/execute": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Execute Device Method
         * @description Execute Ophyd device method with coordination check (High Fidelity Channel).
         *
         *     Always returns a confirmed result. Use when confirmation is required.
         *     Raises 404/423/503/500 on various failure modes.
         */
        post: operations["execute_device_method_api_v1_device_execute_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/device/{device_name}/stop": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Stop Device
         * @description Stop a device (calls the device's stop() method with coordination check).
         */
        post: operations["stop_device_api_v1_device__device_name__stop_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/devices": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Devices
         * @description List available devices (proxied from configuration service).
         */
        get: operations["list_devices_api_v1_devices_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/devices/{device_name}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Device
         * @description Get device metadata (proxied from configuration service).
         */
        get: operations["get_device_api_v1_devices__device_name__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/devices/{device_name}/bundle": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Device Bundle
         * @description Get hierarchical device component tree for building control UIs.
         */
        get: operations["get_device_bundle_api_v1_devices__device_name__bundle_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/device/{device_path}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Access Nested Device
         * @description Access nested device component (e.g. motor1.user_readback).
         *
         *     Coordination-checked for writes; 404/423/503/500 on failure modes.
         */
        post: operations["access_nested_device_api_v1_device__device_path__post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/device/{device_path}/value": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Nested Device Value
         * @description Get nested device component value (read-only, no coordination check).
         */
        get: operations["get_nested_device_value_api_v1_device__device_path__value_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * CommandMode
         * @description Command execution mode for PV writes.
         * @enum {string}
         */
        CommandMode: "put-completion" | "fire-and-forget";
        /**
         * DeviceCommandRequest
         * @description Request to execute a device method (High Fidelity Channel).
         *
         *     use_put=False (default): ophyd set() waits for completion.
         *     use_put=True: ophyd put() returns immediately.
         */
        DeviceCommandRequest: {
            /** Device Name */
            device_name: string;
            /** Method */
            method: string;
            /** Args */
            args?: unknown[];
            /** Kwargs */
            kwargs?: Record<string, never>;
            /** Timeout */
            timeout?: number | null;
            /**
             * Use Put
             * @default false
             */
            use_put: boolean;
        };
        /**
         * DeviceCommandResponse
         * @description Response from device command execution.
         */
        DeviceCommandResponse: {
            /** Device Name */
            device_name: string;
            /** Method */
            method: string;
            /** Success */
            success: boolean;
            /** Result */
            result?: unknown;
            /**
             * Timestamp
             * Format: date-time
             */
            timestamp: string;
            /** Coordination Checked */
            coordination_checked: boolean;
            /** Message */
            message?: string | null;
            /**
             * Use Put
             * @default false
             */
            use_put: boolean;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /**
         * HealthResponse
         * @description Health check response for the merged service.
         */
        HealthResponse: {
            /**
             * Status
             * @default healthy
             */
            status: string;
            /**
             * Timestamp
             * Format: date-time
             */
            timestamp: string;
            /** Coordination Service Available */
            coordination_service_available: boolean;
            /**
             * Active Subscriptions
             * @default 0
             */
            active_subscriptions: number;
            /**
             * Connected Pvs
             * @default 0
             */
            connected_pvs: number;
            /**
             * Websocket Connections
             * @default 0
             */
            websocket_connections: number;
        };
        /**
         * NestedDeviceRequest
         * @description Request to access nested device component.
         */
        NestedDeviceRequest: {
            /**
             * Method
             * @default read
             */
            method: string;
            /** Value */
            value?: unknown | null;
            /** Timeout */
            timeout?: number | null;
        };
        /**
         * NestedDeviceResponse
         * @description Response from nested device access.
         */
        NestedDeviceResponse: {
            /** Device Path */
            device_path: string;
            /** Method */
            method: string;
            /** Success */
            success: boolean;
            /** Result */
            result?: unknown;
            /**
             * Timestamp
             * Format: date-time
             */
            timestamp: string;
            /** Message */
            message?: string | null;
        };
        /**
         * PVSetRequest
         * @description Request to set a PV value (Low Fidelity Channel).
         *
         *     Completion modes:
         *     - wait=False, use_complete=False (default): fire-and-forget — issue write, return.
         *     - wait=True,  use_complete=False: block a CA thread until put finishes.
         *     - use_complete=True: put-with-callback — CA thread is freed; service polls
         *       for completion via the pyepics put-callback mechanism. Preferred for
         *       long puts over HTTP because no worker thread is held.
         *
         *     `connection_timeout` bounds how long we wait to establish CA connection;
         *     separate from `timeout` which bounds the put itself.
         *
         *     `ftype` forces a non-native DBR type on the wire (rare, e.g. when an IOC
         *     expects CHAR waveforms represented differently). Leave None for native.
         */
        PVSetRequest: {
            /**
             * Pv Name
             * @description EPICS PV name
             */
            pv_name: string;
            /**
             * Value
             * @description Value to set
             */
            value: unknown;
            /**
             * Wait
             * @description Block the CA thread until put completion
             * @default false
             */
            wait: boolean;
            /**
             * Timeout
             * @description Put timeout in seconds (used with wait=True or use_complete=True)
             */
            timeout?: number | null;
            /**
             * Connection Timeout
             * @description Max seconds to wait for CA connection (pyepics default 5s)
             */
            connection_timeout?: number | null;
            /**
             * Use Complete
             * @description If True, wait for put via pyepics put-callback instead of blocking a CA thread. Overrides `wait` (always waits) but frees the worker.
             * @default false
             */
            use_complete: boolean;
            /**
             * Ftype
             * @description Force non-native DBR type (power-user knob; leave null for native)
             */
            ftype?: number | null;
        };
        /**
         * PVSetResponse
         * @description Response from PV set operation.
         */
        PVSetResponse: {
            /** Pv Name */
            pv_name: string;
            /** Success */
            success: boolean;
            /** Value Set */
            value_set: unknown;
            /**
             * Timestamp
             * Format: date-time
             */
            timestamp: string;
            /** Coordination Checked */
            coordination_checked: boolean;
            mode: components["schemas"]["CommandMode"];
            /** Message */
            message?: string | null;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_check_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
    get_stats_api_v1_stats_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    set_pv_api_v1_pv_set_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PVSetRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PVSetResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_pv_value_from_controller_api_v1_pv__pv_name__value_get: {
        parameters: {
            query?: {
                /** @description Override Accept header. 'json' or 'binary' (octet-stream). */
                format?: string | null;
                /** @description Return the string representation (e.g. enum label) */
                as_string?: boolean;
                /** @description Max waveform elements to return */
                count?: number | null;
                /** @description Return arrays as numpy.ndarray (JSON-serialized to list) */
                as_numpy?: boolean;
                /** @description Use cached monitor value. Default false matches the one-shot semantics of this endpoint; set true to share a monitor with any existing subscription (note: pyepics auto-installs a permanent CA monitor the first time this is true for a PV). */
                use_monitor?: boolean;
                /** @description CA get timeout in seconds */
                timeout?: number;
                /** @description CA connection timeout in seconds */
                connection_timeout?: number;
                /** @description Force non-native DBR type (power user) */
                ftype?: number | null;
            };
            header?: never;
            path: {
                pv_name: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_monitored_pv_value_api_v1_pvs__pv_name__value_get: {
        parameters: {
            query?: {
                /** @description Override Accept header. 'json' or 'binary' (octet-stream). */
                format?: string | null;
            };
            header?: never;
            path: {
                pv_name: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_connected_pvs_api_v1_pvs_connected_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": string[];
                };
            };
        };
    };
    execute_device_method_api_v1_device_execute_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DeviceCommandRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DeviceCommandResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    stop_device_api_v1_device__device_name__stop_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                device_name: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DeviceCommandResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_devices_api_v1_devices_get: {
        parameters: {
            query?: {
                /** @description Filter by ophyd class name */
                device_class?: string | null;
                /** @description Filter by Readable */
                readable?: boolean | null;
                /** @description Filter by Movable */
                movable?: boolean | null;
                /** @description Filter by Flyable */
                flyable?: boolean | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_device_api_v1_devices__device_name__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                device_name: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_device_bundle_api_v1_devices__device_name__bundle_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                device_name: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    access_nested_device_api_v1_device__device_path__post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                device_path: string;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["NestedDeviceRequest"] | null;
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NestedDeviceResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_nested_device_value_api_v1_device__device_path__value_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                device_path: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
